function createInstrPage(text){
    return ["<div align=center><div class = 'center_text'; style = 'width: 85vw';>" + text + "<br></div>"]
  }

function instructions1(){
    //Part 1: Explain
    p1 = 0.5; amount1 = 25
    p2 = 0.25; amount2 = 66; p3 = 0.75; amount3 = 22; p4 = 0.4; amount4 = 41; 
    p5 = 0.6; amount5 = 48; p6 = 0.8; amount6 = 36
    p7 = 0.55; amount7 = 49; p8 = 0.35; amount8 = 77
    p9= 0.45; amount9 = 18; p10 = 0.7; amount10 = 21; p11 = 0.2, amount11 = 63

    return ['Welcome to the experiment!<br><br> In order to understand the task fully, please read the instructions carefully.<br><br>Press <b>next</b> or <b>spacebar</b> to continue.<br><br>',
    'In this experiment, you will choose between different gambles.<br><br>Each trial will give you a certain chance to earn money. Your goal is to accrue as much money as possible.<br><br>The top 5% of participants with the highest scores will receive $15 Amazon gift cards.<br><br>',
    'Your task is to decide between different gambles.<br><br>For example, would you rather have a:<br><br>30% of winning $80<br><br>OR<br><br>60% of winning $40?<br><br>',
    'These gambles will be presented as <b>colored circles</b>.<br><br>For example, in the gamble below, there is a '+p1*100+'% of winning $'+amount1+' and a '+(1-p1)*100+'% of winning nothing.<br><br><div class="piechart" style = "background-image: conic-gradient(green '+360*p1+'deg, red 0)"><div class="border"><h4 style = "position:relative; left: '+calc_amount_pos(p1).left+'%; top: '+calc_amount_pos(p1).top+'%;">$'+amount1+'</h4></div></div><br><br>In the circle above, the shaded <span class = "greenText">green</span> area represents the probability of winning $'+amount1+'.<br>Since the circle is 1/2 <span class = "greenText">green</span>, the probability of winning 25 points is 50%. <br><br>The shaded <span class = "redText">red</span> area indicates the probability of winning nothing. <br> Since the circle is 1/2 <span class = "redText">red</span>, there is a 50% chance of winning nothing.<br><br>',
    'For each trial, you will choose between three gambles.<br><br>You will make this choice in two steps:<br><br><b>Step 1:</b> Choose between the first two gambles.<br><br><b>Step 2:</b> Choose between your first selection and the third gamble.<br><br>',
    'You will now see an example of how the gambles will be presented.<br><br>Press <b>next</b> or <b>spacebar</b> to continue.<br><br>',
    '<br>At the beginning of each trial, you will see two gambles as shown below: <br><br><br><div style = "display:flex; width:60vw; justify-content:space-between;"><div class="piechart" style = "background-image: conic-gradient(green '+360*p2+'deg, red 0)"><div class="border"><h4 style = "position:relative; left:'+25*Math.cos((180*p2 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p2 - 90)*Math.PI/180)+'%;">$'+amount2+'</h4></div></div><div class="piechart" style= "background-image: conic-gradient(green '+360*p3+'deg, red 0)"><div class="border"><h4 style = "position:relative; left: '+25*Math.cos((180*p3 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p3 - 90)*Math.PI/180)+'%;">$'+amount3+'</h4></div></div></div><br><br>In the example above, you can choose either a '+p2*100+'% chance of winning $'+amount2+' and a '+(1-p2)*100+'% chance of winning nothing,<br>OR a '+p3*100+'% chance of winning $'+amount3+' and a '+(1-p3)*100+'% chance of winning nothing.<br><br>',
    '<br>If you choose the left gamble, then the left gamble will stay on the screen and move to the middle.<br><br><br><div class="piechart" style = "background-image: conic-gradient(green '+360*p2+'deg, red 0)"><div class="border" style="opacity: 1; border-color: white; border-width: 1px; border-style: dashed;"><h4 style = "position:relative; left:'+25*Math.cos((180*p2 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p2 - 90)*Math.PI/180)+'%;">$'+amount2+'</h4></div></div><br><br>This is to remind you that the trial is not over.<br><br>Since you did not select the right gamble, the right gamble will disappear.<br><br>',
    '<br><br><div style="display: flex; align-items: center; justify-content: center;"><span style="font-size: 48px; color: white; margin-right: 30px;">&#8592;</span><div class="piechart" style = "background-image: conic-gradient(green '+360*p2+'deg, red 0)"><div class="border"><h4 style = "position:relative; left:'+25*Math.cos((180*p2 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p2 - 90)*Math.PI/180)+'%;">$'+amount2+'</h4></div></div><span style="font-size: 48px; color: white; margin-left: 30px;">&#8594;</span></div><br><br>The gamble you chose first will then move to the left or the right.<br><br>',
    '<br><br><div style = "display:flex; width:60vw; justify-content:space-between;"><div class="piechart" style = "opacity: 0; background-image: conic-gradient(green '+360*p4+'deg, red 0)"><div class="border"><h4 style = "position:relative; left:'+25*Math.cos((180*p4 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p4 - 90)*Math.PI/180)+'%;">$'+amount4+'</h4></div></div><div class="piechart" style= "background-image: conic-gradient(green '+360*p2+'deg, red 0)"><div class="border"><h4 style = "position:relative; left: '+25*Math.cos((180*p2 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p2 - 90)*Math.PI/180)+'%;">$'+amount2+'</h4></div></div></div><br><br>In this case, the gamble moved to the right.<br><br>',
    '<br>Next, the third gamble will appear, and you can make your final choice between these two gambles.<br><br><br><div style = "display:flex; width:60vw; justify-content:space-between;"><div class="piechart" style = "background-image: conic-gradient(green '+360*p4+'deg, red 0)"><div class="border"><h4 style = "position:relative; left:'+25*Math.cos((180*p4 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p4 - 90)*Math.PI/180)+'%;">$'+amount4+'</h4></div></div><div class="piechart" style= "background-image: conic-gradient(green '+360*p2+'deg, red 0)"><div class="border"><h4 style = "position:relative; left: '+25*Math.cos((180*p2 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p2 - 90)*Math.PI/180)+'%;">$'+amount2+'</h4></div></div></div><br><br>The gamble you choose here will be your final selection.</b><br><br>We will use only your final selections to determine how much money you earned.<br><br>',
    'Before each trial begins, you will see a fixation cross (+) in the center of the screen.<br><br>This lets you know that a new trial is about to start.<br><br>',
    '<br><br>When choosing a gamble, press the <b>F key</b> to select the gamble on the left and the <b>J key</b> to select the gamble on the right.<br><br><br><br><div style = "display:flex; width:60vw; justify-content:space-between;"><div style ="display: flex; flex-direction:column"><div class="piechart" style = "background-image: conic-gradient(green '+360*p7+'deg, red 0)"><div class="border"><h4 style = "position:relative; left:'+25*Math.cos((180*p7 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p7 - 90)*Math.PI/180)+'%;">$'+amount7+'</h4></div></div><br><br><b>Press the F key</b></div><div style ="display: flex; flex-direction:column"><div class="piechart" style= "background-image: conic-gradient(green '+360*p8+'deg, red 0)"><div class="border"><h4 style = "position:relative; left: '+25*Math.cos((180*p8 - 90)*Math.PI/180)+'%; top: '+25*Math.sin((180*p8 - 90)*Math.PI/180)+'%;">$'+amount8+'</h4></div></div><br><br><b>Press the J key</b></div></div><br><br><br><br><b><u>The keys are always based on position, regardless of which gamble is there.</u></b><br><br>',
    '<u>Time to practice!</u> <br><br> You will now perform '+trials.practice+' practice trials.<br><br><b>As a reminder, on each trial, you will first choose between two gambles, and then between your selection and a third gamble. The second choice you make will be your final selection.</b><br><br>Press space to continue.<br><br>',   
    ].map(x => createInstrPage(x))}


function instructions2(){
    return [
    "From now on, you will have to make each choice within  "+times.time_to_choose/1000 +" seconds.<br><br>If you do not choose an option on either the first or second selection in time, your score for that trial will be $0.<br><br>If you do not choose an option on the first selection, then you will start a new trial, but will have to wait for the new trial to begin.<br><br>",
    'In order to determine how much money you won, '+trials.outcome+ ' trials will be randomly selected at the end of the experiment.<br><br>The computer will then use the probabilities of the chosen gambles to determine whether you win or lose for each randomly selected trial.<br><br>Since you do not know which trials will be selected, you will have to pay attention on all of them. <br><br>',
    "You'll complete "+trials.total+" trials during the study, which will approximately take "+times.length_of_experiment+" minutes to complete. <br><br> And again, to encourage you to amass many points, the top 5% of participants with the highest scores will win $15 Amazon gift cards.<br><br>",
    "You are now ready for the experiment. <br><br>Press space or click the next button to begin! <br><br>",
].map(x => createInstrPage(x))}
